version: '3'

services:
  Telegram-Jellyfin-Bot:
    build:
      context: .
    volumes:
      - ./User.json:/app/User.json
      - ./RegCode.json:/app/RegCode.json
      - ./config.toml:/app/config.toml
    container_name: Telegram-Jellyfin-Bot
    network_mode: host
    restart: always
